In [423]:
#initialize the weights for now randomly
#first a testing right now
#784 input, 100 nuerals in the hidden layer, 10 output
#make the network working by initialize small divide it by 800.
def initializeWeight1():
    weights1=numpy.random.random((784+1, 100))/800
    #1 for bias
    return weights1
def initializeWeight2():
    weights2=numpy.random.random((100+1,10))/800
    #1 for bias 
    return weights2
step=0.01


In [384]:
weights1=initializeWeight1()
weights1Old=weights1
weights2=initializeWeight2()
weights2Old=weights2


In [385]:
import math
import numpy as np
import pandas as pd


In [386]:
def sigmoidFunc(x):
    return math.tanh(x)
    

In [387]:
def dsigmoidFunc(sigmoidValue):
    return 1-sigmoidValue**2

In [388]:
training_set=pd.read_csv('../train.csv')
labels=np.array(training_set)[:,0]
features=np.array(training_set)[:,0:].astype(float)/255
features[:,0]=[1.0]*42000   #add this one for bias

In [389]:
#feedForward1
def feedForward1(pointChoseFromDataset):
    
    firstLayerResult=[]
    firstLayerResult.append(1)
    #this is for the bias part
    for i in range(100):
        temp=weights1[:,i];
        firstLayerResult.append(sigmoidFunc(sum(p*q for p,q in zip(pointChoseFromDataset,temp))))
    return firstLayerResult

        


In [390]:
#feedForward2
def feedForward2(firstLayerResult):
    secondLayerResult=[]
    for i in range(10):
        temp=weights2[:,i]
        secondLayerResult.append(sigmoidFunc(sum(p*q for p,q in zip(firstLayerResult,temp))))
    return secondLayerResult

        

In [391]:
def get10LableResultFromLabels(stochasticPoint):
    #this is will return a size 10 array with for that stochastic point
    finalResult=labels[stochasticPoint]
    arrayResult=[0]*10
    for j in range(10):
        if(finalResult==j):
            arrayResult[j]=1
            break
    return arrayResult


In [424]:
#this is to update the weights
def updateMatrix(toBeUpdatedMatrix,delta,previousLayerX):
    #this will lose the previous weights1
    for i in range(101):
        for j in range(10):
            toBeUpdatedMatrix[i][j]=toBeUpdatedMatrix[i][j]-step*delta[j]*previousLayerX[i]
    return toBeUpdatedMatrix


In [445]:
#run back propagation
def backPropagation():
    stochasticPoint=random.randint(1,42000)
    pointChoseFromDataset=features[stochasticPoint]
    labelResult=get10LableResultFromLabels(stochasticPoint)
    firstLayerResult=feedForward1(pointChoseFromDataset)
    result=feedForward2(firstLayerResult)
    deltaLastLayer=np.multiply(np.subtract(np.array(result),labelResult),np.subtract(1,np.multiply(result,result)))
    updateMatrix(weights2,deltaLastLayer,firstLayerResult)
    deltaFirstLayer=np.multiply(np.subtract(1,np.multiply(firstLayerResult,firstLayerResult)),np.dot(weights2Old,deltaLastLayer))
    #is this one should be weights old or weights new?
    updateMatrix(weights1,deltaFirstLayer,pointChoseFromDataset)
    return test    

In [446]:
test=backPropagation()

In [452]:
test

array([[  8.13052189e-04,   9.46232239e-05,   1.22590798e-03, ...,
          1.09342097e-03,   5.86911512e-04,   8.81946303e-04],
       [  4.85615541e-04,   5.03186633e-04,   1.16888400e-03, ...,
          8.03803242e-04,   1.44680603e-04,   1.24979548e-03],
       [  3.36836137e-04,   5.39340749e-04,   2.73813964e-04, ...,
          3.17735659e-04,   6.17129310e-05,   8.26498619e-04],
       ..., 
       [  6.00564854e-04,   2.62229864e-04,   1.16802882e-03, ...,
          1.03751372e-03,   1.24522695e-03,   7.22229065e-04],
       [  4.83239213e-04,   5.20835092e-04,   7.05765424e-04, ...,
          7.30167613e-04,   5.58517139e-04,   6.05436980e-04],
       [  4.62898595e-04,   9.39738457e-04,   7.04114820e-04, ...,
          9.07841920e-04,   1.18141792e-03,   1.16241906e-03]])

In [453]:
weights1Old

array([[  8.13052189e-04,   9.46232239e-05,   1.22590798e-03, ...,
          1.09342097e-03,   5.86911512e-04,   8.81946303e-04],
       [  4.85615541e-04,   5.03186633e-04,   1.16888400e-03, ...,
          8.03803242e-04,   1.44680603e-04,   1.24979548e-03],
       [  3.36836137e-04,   5.39340749e-04,   2.73813964e-04, ...,
          3.17735659e-04,   6.17129310e-05,   8.26498619e-04],
       ..., 
       [  6.00564854e-04,   2.62229864e-04,   1.16802882e-03, ...,
          1.03751372e-03,   1.24522695e-03,   7.22229065e-04],
       [  4.83239213e-04,   5.20835092e-04,   7.05765424e-04, ...,
          7.30167613e-04,   5.58517139e-04,   6.05436980e-04],
       [  4.62898595e-04,   9.39738457e-04,   7.04114820e-04, ...,
          9.07841920e-04,   1.18141792e-03,   1.16241906e-03]])

In [429]:
#very good example to do dot production
test1=np.array([[1,2,3],[4,5,6],[7,8,9]])
test2=np.array([2,2,2])
final=np.dot(test1,test2)
final


array([12, 30, 48])