In [297]:
import numpy as np
import math
import pandas as pd
NoOfNodesFirstLayer=20
alpha=0.1


    

In [298]:
#initialize weight

def initializeWeight1():
    weights=(np.random.rand(785,NoOfNodesFirstLayer+1)*2-1)
    return weights
def initializeWeight2():
    weights=(np.random.rand(NoOfNodesFirstLayer+1,10)*2-1)
    return weights
def secondLayerSigmoid(x):
    return 1/(1+math.exp(x*-1))
def firstLayerSigmoid(x):
    return math.tanh(x)
def dfirstLayerSigmoid(x):
    return 1-(math.tanh(x))**2
def dsecondLayerSigmoid(x):
    return 1/(2+math.exp(x)+math.exp(x*-1))

In [299]:
weights1=initializeWeight1()
weights2=initializeWeight2()
weights1old=weights1
weights2old=weights2

array([[  4.65604103e-01,   7.93124798e-01,  -6.85439657e-01, ...,
         -4.46146952e-02,   8.24343307e-01,   1.69828706e-05],
       [ -7.51644679e-01,  -4.50830492e-01,   4.51155309e-01, ...,
          8.30130785e-02,   1.04384536e-02,  -8.18445170e-01],
       [  9.37086865e-01,   5.87900595e-01,   9.98965685e-02, ...,
          3.80946568e-01,   5.51769936e-01,   8.30277350e-01],
       ..., 
       [ -4.43483255e-01,   6.39019806e-01,  -5.21045986e-01, ...,
          4.61882972e-01,  -7.94949326e-01,   8.24136003e-01],
       [  4.90303571e-01,  -7.95480640e-01,   2.17073561e-01, ...,
         -6.81241938e-02,   9.17892271e-01,  -6.28627132e-01],
       [  4.50347233e-01,   9.79824729e-01,  -4.44329871e-01, ...,
          3.71502438e-01,   5.50273376e-01,   9.79497823e-01]])

In [301]:
training_set=pd.read_csv('../train.csv')
labels=np.array(training_set)[:,0]
features=np.array(training_set)[:,0:].astype(float)/255
features[:,0]=[1.0]*42000

In [302]:
#this will return an array after the first layer
def firstLayerAction(input,weights,NoOfNodesFirstLayer):
    firstLayerResult=[]
    firstLayerResult.append(1)
    for i in range(NoOfNodesFirstLayer):
        temp=weights1[:,i]
        firstLayerResult.append(firstLayerSigmoid(np.dot(temp,input)))
    return firstLayerResult



In [303]:
def firstLayerSum(input,weights,NoOfNodesFirstLayer):
    firstLayerSum=[]
    #it does not have the biased part
    for i in range(NoOfNodesFirstLayer):
        temp=weights1[:,i]
        firstLayerSum.append(np.dot(temp,input))
    return firstLayerSum
    

In [304]:
def secondLayerAction(input,weights):
    outputLayerResult=[]
    for i in range(10):
        temp=weights[:,i]
        outputLayerResult.append(secondLayerSigmoid(np.dot(temp,input)))
    return outputLayerResult

In [305]:
def secondLayerSum(input,weights):
    outputLayerResult=[]
    for i in range(10):
        temp=weights[:,i]
        outputLayerResult.append(np.dot(temp,input))
    return outputLayerResult

In [307]:
def get10LableResultFromLabels(output):
    #this is will return a size 10 array with for that stochastic point
    returnArray=[]
    for i in range(10):
        if(output==i):
            returnArray.append(1)
        else:
            returnArray.append(0)
    return returnArray
        

In [324]:
def updateWeights(a2,realOutput,estimatedOutput,outputFromHiddenLayer,sumInFirstLayer,inputLayer):
    #this is update weight1:
    deltaK2Array=[]
    for k in range(10):
        deltaK2=(realOutput[k]-estimatedOutput[k])*dsecondLayerSigmoid(a2[k])
        deltaK2Array.append(deltaK2)
        for j in range(NoOfNodesFirstLayer+1):
            weights2[j][k]=weights2[j][k]+alpha*outputFromHiddenLayer[j]*deltaK2
    for j in range(NoOfNodesFirstLayer+1):
        deltaJ1=np.dot(weights2[j,:],deltaK2Array)*dfirstLayerSigmoid(sumInFirstLayer[j])
        for i in range(785):
            weights1[i][j]=weights1[i][j]+alpha*inputLayer[i]*deltaJ1
    

In [325]:
a2=secondLayerSum(firstLayerAction(features[1],weights1,20),weights2)

In [326]:
weights1

array([[  4.65604103e-01,   7.93124798e-01,  -6.85439657e-01, ...,
         -4.46148741e-02,   8.24356147e-01,   1.68246263e-05],
       [ -7.51644679e-01,  -4.50830492e-01,   4.51155309e-01, ...,
          8.30130785e-02,   1.04384536e-02,  -8.18445170e-01],
       [  9.37086865e-01,   5.87900595e-01,   9.98965685e-02, ...,
          3.80946568e-01,   5.51769936e-01,   8.30277350e-01],
       ..., 
       [ -4.43483255e-01,   6.39019806e-01,  -5.21045986e-01, ...,
          4.61882972e-01,  -7.94949326e-01,   8.24136003e-01],
       [  4.90303571e-01,  -7.95480640e-01,   2.17073561e-01, ...,
         -6.81241938e-02,   9.17892271e-01,  -6.28627132e-01],
       [  4.50347233e-01,   9.79824729e-01,  -4.44329871e-01, ...,
          3.71502438e-01,   5.50273376e-01,   9.79497823e-01]])

In [327]:
realOutput=get10LableResultFromLabels(labels[1])

In [328]:
realOutput

[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [329]:
estimatedOutput=[secondLayerSigmoid(x) for x in a2]

In [330]:
estimatedOutput

[0.5753317594103795,
 0.47762747993357973,
 0.10564720681575122,
 0.0010793223424144373,
 0.9297396289403271,
 0.30336287284918184,
 0.5646607604055937,
 0.760330759892658,
 0.43989699922121683,
 0.36575159478043917]

In [331]:
outputFromHiddenLayer=firstLayerAction(features[1],weights1,20)

In [332]:
outputFromHiddenLayer

[1,
 0.999999996610482,
 0.9999999999988203,
 0.9999999999989609,
 -0.9804084830902202,
 -0.999999997889515,
 0.9999999640082823,
 0.9999999999999999,
 -0.5644805171197955,
 -0.9999999327776901,
 -0.9999998059102786,
 -0.9999999229217853,
 0.9947071183478324,
 0.9999999990822867,
 0.9999877294210974,
 0.9359517797131174,
 -0.9973855520357313,
 0.9985375347783767,
 -0.9999951378670233,
 0.9998177319158804,
 0.9999966803736781]

In [333]:
sumInFirstLayer=[]
sumInFirstLayer.append(np.arctanh(1))
for x in firstLayerSum(features[1],weights1,20):
    sumInFirstLayer.append(x)


In [334]:
inputLayer=features[1]


In [335]:
updateWeights(a2,realOutput,estimatedOutput,outputFromHiddenLayer,sumInFirstLayer,inputLayer)
    

In [336]:
weights1old.shape

(785, 21)

In [337]:
assert(weights1.all()==weights1old.all())

In [72]:
test=features[1]

In [73]:
from PIL import Image

In [77]:
img=Image.new('RGB',(28,28),"white")
pixels=img.load()



In [79]:
for i in range(img.size[0]):
    for j in range(img.size[1]):
        pixels[i,j]=(i,j,test[i*28+j])
img.show()

In [76]:
test

array([  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,  18,  30, 137, 137, 192,  86,  72,
         1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,  13,  86, 250, 254, 254, 254, 254,
       217, 246, 151,  32,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  16, 179, 254, 254, 25